# Generated by Django 4.1 on 2022-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesapp', '0002_productmodel_subproductmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproductmodel',
            old_name='sub_productname',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='orderedproductmodel',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
    ]
