# Generated by Django 4.1 on 2022-08-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Salesapp', '0004_remove_ordermodel_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
