# Generated by Django 4.1 on 2022-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesapp', '0005_ordermodel_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproductmodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subproductmodel',
            name='stock',
            field=models.FloatField(default=0.0),
        ),
    ]
