# Generated by Django 4.1 on 2022-08-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesapp', '0006_remove_orderedproductmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproductmodel',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
