# Generated by Django 4.1 on 2022-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesapp', '0007_orderedproductmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='have_subproduct',
            field=models.BooleanField(default=False),
        ),
    ]
