# Generated by Django 4.1 on 2022-09-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesapp', '0009_orderedproductmodel_subproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductmodel',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproductmodel',
            name='subproduct_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
