# Generated by Django 4.1 on 2022-09-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salesapp', '0010_alter_orderedproductmodel_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductmodel',
            name='product_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
